version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /app/docker-credential/username
    DOCKER_REGISTRY_PASSWORD: /app/docker-credential/password
    DOCKER_REGISTRY_URL: /app/docker-credential/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "$DOCKER_REGISTRY_USERNAME"
      - echo "$DOCKER_REGISTRY_PASSWORD"
      - echo "$DOCKER_REGISTRY_URL"
      - echo "build simple python application"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest"
  post_build:
    commands:
      - echo "build successful"